ALTER TYPE "RepairStatus" ADD VALUE IF NOT EXISTS 'PAS_ENCORE_RECU_CLIENT';

ALTER TABLE "ProAccount"
  ADD COLUMN IF NOT EXISTS "shopSlotDurationMinutes" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "shopMaxAppointmentsPerSlot" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "PendingProSignup"
  ADD COLUMN IF NOT EXISTS "shopSlotDurationMinutes" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "shopMaxAppointmentsPerSlot" INTEGER NOT NULL DEFAULT 1;
